CATALOG: mk_fiddles
DATABRICKS_MODEL: databricks-claude-3-7-sonnet
GENIE_SPACE_PRODUCT_INV_ID: 01f0408efb0c19099ce7e958563c175a
GENIE_SPACE_STORE_PERFORMANCE_ID: 01f0408ecdfe1d2595651a15a88f909a
MLFLOW_EXPERIMENT_ID: "2933242203415888"
SCHEMA: genie_multi_agent
